language: cpp
os: linux
dist: bionic
arch:
  - amd64
compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
      - dos2unix
      - curl
      - libpcsclite-dev
      - libcurl4
      - libcurl4-openssl-dev

git:
  depth: 3
  quiet: true

branches:
  only:
    - master

script:
  - make -j4
  - source src/tstools/release-x86_64/setenv.sh && tsversion --version=all
  - make test
