language: cpp

git:
  depth: 3
  quiet: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - dos2unix
      - curl
      - tar
      - libpcsclite-dev
      - libcurl4
      - libcurl4-openssl-dev
  homebrew:
    packages:
      - gnu-sed
      - grep
      - dos2unix
      - pcsc-lite

matrix:
  include:
    - name: "Linux with GCC"
      os: linux
      dist: bionic
      arch: amd64
      compiler: gcc
    - name: "Linux with clang"
      os: linux
      dist: bionic
      arch: amd64
      compiler: clang
    - name: "macOS with clang"
      os: osx
      osx_image: xcode11.3
      compiler: clang

script:
  - make -j4
  - source src/tstools/release-x86_64/setenv.sh && tsversion --version=all
  - make test
  - mkdir -p ../tsduck-test
  - curl -s -L https://github.com/tsduck/tsduck-test/tarball/master | tar xz --strip 1 -C ../tsduck-test
  - make test-suite
